// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gofundme/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateGofundme struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Goal    uint64 `protobuf:"varint,2,opt,name=goal,proto3" json:"goal,omitempty"`
	Start   string `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End     string `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *MsgCreateGofundme) Reset()         { *m = MsgCreateGofundme{} }
func (m *MsgCreateGofundme) String() string { return proto.CompactTextString(m) }
func (*MsgCreateGofundme) ProtoMessage()    {}
func (*MsgCreateGofundme) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5586d6ac7b0447d, []int{0}
}
func (m *MsgCreateGofundme) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateGofundme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateGofundme.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateGofundme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateGofundme.Merge(m, src)
}
func (m *MsgCreateGofundme) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateGofundme) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateGofundme.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateGofundme proto.InternalMessageInfo

func (m *MsgCreateGofundme) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateGofundme) GetGoal() uint64 {
	if m != nil {
		return m.Goal
	}
	return 0
}

func (m *MsgCreateGofundme) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *MsgCreateGofundme) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type MsgCreateGofundmeResponse struct {
}

func (m *MsgCreateGofundmeResponse) Reset()         { *m = MsgCreateGofundmeResponse{} }
func (m *MsgCreateGofundmeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateGofundmeResponse) ProtoMessage()    {}
func (*MsgCreateGofundmeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5586d6ac7b0447d, []int{1}
}
func (m *MsgCreateGofundmeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateGofundmeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateGofundmeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateGofundmeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateGofundmeResponse.Merge(m, src)
}
func (m *MsgCreateGofundmeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateGofundmeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateGofundmeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateGofundmeResponse proto.InternalMessageInfo

type MsgDonateFund struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id       uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Donation string `protobuf:"bytes,3,opt,name=donation,proto3" json:"donation,omitempty"`
}

func (m *MsgDonateFund) Reset()         { *m = MsgDonateFund{} }
func (m *MsgDonateFund) String() string { return proto.CompactTextString(m) }
func (*MsgDonateFund) ProtoMessage()    {}
func (*MsgDonateFund) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5586d6ac7b0447d, []int{2}
}
func (m *MsgDonateFund) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDonateFund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDonateFund.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDonateFund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDonateFund.Merge(m, src)
}
func (m *MsgDonateFund) XXX_Size() int {
	return m.Size()
}
func (m *MsgDonateFund) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDonateFund.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDonateFund proto.InternalMessageInfo

func (m *MsgDonateFund) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDonateFund) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgDonateFund) GetDonation() string {
	if m != nil {
		return m.Donation
	}
	return ""
}

type MsgDonateFundResponse struct {
}

func (m *MsgDonateFundResponse) Reset()         { *m = MsgDonateFundResponse{} }
func (m *MsgDonateFundResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDonateFundResponse) ProtoMessage()    {}
func (*MsgDonateFundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5586d6ac7b0447d, []int{3}
}
func (m *MsgDonateFundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDonateFundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDonateFundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDonateFundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDonateFundResponse.Merge(m, src)
}
func (m *MsgDonateFundResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDonateFundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDonateFundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDonateFundResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateGofundme)(nil), "cosmonaut.gofundme.gofundme.MsgCreateGofundme")
	proto.RegisterType((*MsgCreateGofundmeResponse)(nil), "cosmonaut.gofundme.gofundme.MsgCreateGofundmeResponse")
	proto.RegisterType((*MsgDonateFund)(nil), "cosmonaut.gofundme.gofundme.MsgDonateFund")
	proto.RegisterType((*MsgDonateFundResponse)(nil), "cosmonaut.gofundme.gofundme.MsgDonateFundResponse")
}

func init() { proto.RegisterFile("gofundme/tx.proto", fileDescriptor_c5586d6ac7b0447d) }

var fileDescriptor_c5586d6ac7b0447d = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0xed, 0xb4, 0xf5, 0x75, 0xc1, 0x62, 0x07, 0xc5, 0xd8, 0xc2, 0x50, 0xb2, 0x2a, 0x2e, 0x26,
	0x50, 0xc1, 0x0f, 0x50, 0x51, 0x37, 0xd9, 0x04, 0xdc, 0xb8, 0x4b, 0x33, 0xe3, 0x18, 0x68, 0x66,
	0x42, 0x66, 0x02, 0xf1, 0x2f, 0xfc, 0x2c, 0x97, 0x5d, 0xba, 0x94, 0x64, 0xed, 0x3f, 0x48, 0x62,
	0x92, 0xaa, 0x85, 0xaa, 0xbb, 0x73, 0x6f, 0x4e, 0xce, 0x63, 0xb8, 0x30, 0x14, 0xea, 0x21, 0x95,
	0x2c, 0xe2, 0x8e, 0xc9, 0x68, 0x9c, 0x28, 0xa3, 0xf0, 0x38, 0x50, 0x3a, 0x52, 0xd2, 0x4f, 0x0d,
	0x6d, 0x3e, 0xb6, 0xc0, 0x0e, 0x61, 0xe8, 0x6a, 0x71, 0x99, 0x70, 0xdf, 0xf0, 0x9b, 0x7a, 0x89,
	0x2d, 0xd8, 0x09, 0xca, 0x8d, 0x4a, 0x2c, 0x34, 0x41, 0xd3, 0x3d, 0xaf, 0x19, 0x31, 0x86, 0xbe,
	0x50, 0xfe, 0xc2, 0xea, 0x4e, 0xd0, 0xb4, 0xef, 0x55, 0x18, 0x1f, 0xc2, 0x96, 0x36, 0x7e, 0x62,
	0xac, 0x5e, 0xc5, 0xfd, 0x1c, 0xf0, 0x01, 0xf4, 0xb8, 0x64, 0x56, 0xbf, 0xda, 0x95, 0xd0, 0x1e,
	0xc3, 0xc9, 0x9a, 0x95, 0xc7, 0x75, 0xac, 0xa4, 0xe6, 0xf6, 0x1d, 0xec, 0xbb, 0x5a, 0x5c, 0x29,
	0xe9, 0x1b, 0x7e, 0x9d, 0x4a, 0xb6, 0x21, 0xc3, 0x00, 0xba, 0x21, 0xab, 0x13, 0x74, 0x43, 0x86,
	0x47, 0xb0, 0xcb, 0xca, 0xff, 0x42, 0x25, 0xeb, 0x08, 0xed, 0x6c, 0x1f, 0xc3, 0xd1, 0x37, 0xd9,
	0xc6, 0x6f, 0xf6, 0x8e, 0xa0, 0xe7, 0x6a, 0x81, 0x33, 0x18, 0xfc, 0x28, 0x4f, 0xe9, 0x86, 0xf7,
	0xa2, 0x6b, 0x0d, 0x46, 0xe7, 0xff, 0xe3, 0x37, 0x09, 0xf0, 0x02, 0xe0, 0x4b, 0xdd, 0xd3, 0xdf,
	0x54, 0x56, 0xdc, 0xd1, 0xec, 0xef, 0xdc, 0xc6, 0xed, 0xe2, 0xf6, 0x25, 0x27, 0x68, 0x99, 0x13,
	0xf4, 0x96, 0x13, 0xf4, 0x5c, 0x90, 0xce, 0xb2, 0x20, 0x9d, 0xd7, 0x82, 0x74, 0xee, 0xa9, 0x08,
	0xcd, 0x63, 0x3a, 0xa7, 0x81, 0x8a, 0x9c, 0x56, 0xd7, 0x69, 0xcf, 0x28, 0x5b, 0x41, 0xf3, 0x14,
	0x73, 0x3d, 0xdf, 0xae, 0xae, 0xea, 0xec, 0x23, 0x00, 0x00, 0xff, 0xff, 0x82, 0x5d, 0x37, 0x3d,
	0x6a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateGofundme(ctx context.Context, in *MsgCreateGofundme, opts ...grpc.CallOption) (*MsgCreateGofundmeResponse, error)
	DonateFund(ctx context.Context, in *MsgDonateFund, opts ...grpc.CallOption) (*MsgDonateFundResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateGofundme(ctx context.Context, in *MsgCreateGofundme, opts ...grpc.CallOption) (*MsgCreateGofundmeResponse, error) {
	out := new(MsgCreateGofundmeResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.gofundme.gofundme.Msg/CreateGofundme", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DonateFund(ctx context.Context, in *MsgDonateFund, opts ...grpc.CallOption) (*MsgDonateFundResponse, error) {
	out := new(MsgDonateFundResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.gofundme.gofundme.Msg/DonateFund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateGofundme(context.Context, *MsgCreateGofundme) (*MsgCreateGofundmeResponse, error)
	DonateFund(context.Context, *MsgDonateFund) (*MsgDonateFundResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateGofundme(ctx context.Context, req *MsgCreateGofundme) (*MsgCreateGofundmeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGofundme not implemented")
}
func (*UnimplementedMsgServer) DonateFund(ctx context.Context, req *MsgDonateFund) (*MsgDonateFundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DonateFund not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateGofundme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateGofundme)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateGofundme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.gofundme.gofundme.Msg/CreateGofundme",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateGofundme(ctx, req.(*MsgCreateGofundme))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DonateFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDonateFund)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DonateFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.gofundme.gofundme.Msg/DonateFund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DonateFund(ctx, req.(*MsgDonateFund))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmonaut.gofundme.gofundme.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGofundme",
			Handler:    _Msg_CreateGofundme_Handler,
		},
		{
			MethodName: "DonateFund",
			Handler:    _Msg_DonateFund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gofundme/tx.proto",
}

func (m *MsgCreateGofundme) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateGofundme) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateGofundme) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.End) > 0 {
		i -= len(m.End)
		copy(dAtA[i:], m.End)
		i = encodeVarintTx(dAtA, i, uint64(len(m.End)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Start) > 0 {
		i -= len(m.Start)
		copy(dAtA[i:], m.Start)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Start)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Goal != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Goal))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateGofundmeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateGofundmeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateGofundmeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDonateFund) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDonateFund) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDonateFund) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Donation) > 0 {
		i -= len(m.Donation)
		copy(dAtA[i:], m.Donation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Donation)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDonateFundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDonateFundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDonateFundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateGofundme) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Goal != 0 {
		n += 1 + sovTx(uint64(m.Goal))
	}
	l = len(m.Start)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.End)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateGofundmeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDonateFund) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Donation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDonateFundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateGofundme) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateGofundme: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateGofundme: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Goal", wireType)
			}
			m.Goal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Goal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Start = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.End = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateGofundmeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateGofundmeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateGofundmeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDonateFund) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDonateFund: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDonateFund: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Donation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Donation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDonateFundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDonateFundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDonateFundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
